apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
  labels:
    app: postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
stringData:
  postgres-user: {{ .Values.auth.user | quote }}
  postgres-password: {{ .Values.auth.password | quote }}
  postgres-url: {{ printf "postgresql://%s:%s@postgres:5432/%s" .Values.auth.user .Values.auth.password .Values.auth.database | quote }}
