apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
