"""Cross-collection entity resolution: pool → block → score → adjudicate →
cluster → merge.

Order-independent by design (no sequential graph folding): every entity from
every collection artifact is pooled, candidate pairs are generated by cheap
blocking, scored deterministically, and only the borderline band goes to the
LLM for pair adjudication. Accepted matches are clustered with union-find
under a date-contradiction veto, then one canonical entity is emitted per
cluster. Pooling everything also cleans up name variants the deterministic
within-collection merge deliberately left alone ("Pennsylvania Railroad" vs
"Pennsylvania Railroad Company").

Posture is UNDER-MERGE throughout (docs/kg-conventions.md): agents merge
automatically only on exact normalized-name equality; places and events
never reach the LLM band; any date contradiction vetoes, including
transitively at cluster time.
"""

from __future__ import annotations

import json
import logging
import re
from difflib import SequenceMatcher
from typing import Any

from kggenerator import config

logger = logging.getLogger(__name__)

# Score bands for agent pairs (places/events are exact-match only).
AUTO_THRESHOLD = 0.90      # reached only via exact normalized-name equality
LLM_THRESHOLD = 0.50       # candidates above this (below auto) are adjudicated
CORP_FORM_WORDS = {
    "company": "company", "co": "company", "corporation": "corporation",
    "corp": "corporation", "inc": "incorporated", "incorporated": "incorporated",
    "rail road": "railroad", "rail-road": "railroad",
}
_STOP_TOKENS = {"the", "of", "and", "&"}


# ---------------------------------------------------------------------------
# Normalization and features
# ---------------------------------------------------------------------------

def norm_name(name: str) -> str:
    n = name.lower()
    n = re.sub(r"[.,;:'\"()\[\]]", " ", n)
    n = n.replace("&", " and ")
    n = re.sub(r"\s+", " ", n).strip()
    n = re.sub(r"\s*\b\d{4}\s*-\s*(\d{4})?$", "", n).strip()  # trailing life dates
    for src, dst in CORP_FORM_WORDS.items():
        n = re.sub(rf"\b{src}\b", dst, n)
    return n


def _tokens(name: str) -> set[str]:
    return {t for t in norm_name(name).split() if t not in _STOP_TOKENS}


_CORE_DROP = {"company", "corporation", "incorporated"}


def core_name(name: str) -> str:
    """Normalized name minus corporate-form words — the identity the
    succession veto compares ('Hudson and Boston Railroad Corporation' and
    'Hudson & Boston Railroad Company' share the core name)."""
    return " ".join(t for t in norm_name(name).split() if t not in _CORE_DROP)


def successor_pairs(artifacts: list[dict[str, Any]]) -> set[frozenset[str]]:
    """Core-name pairs the extracted graphs assert succession between.

    A corporate body described as reorganized as / merged into / succeeded
    by another is a DIFFERENT entity from its successor, however similar the
    names — the KG's own hasSuccessor edges are the strongest evidence two
    similarly-named records must NOT merge (Hudson and Berkshire Railroad vs
    the Hudson and Boston Railroad it was reorganized as)."""
    pairs: set[frozenset[str]] = set()
    for art in artifacts:
        names = {e["id"]: e["name"] for e in art["graph"]["entities"]}
        for r in art["graph"]["relations"]:
            if r["type"] in ("hasSuccessor", "isSuccessorOf"):
                ca, cb = core_name(names[r["from"]]), core_name(names[r["to"]])
                if ca != cb:
                    pairs.add(frozenset({ca, cb}))
    return pairs


def succession_veto(
    a: dict[str, Any], b: dict[str, Any], pairs: set[frozenset[str]]
) -> bool:
    for na in _all_names(a):
        for nb in _all_names(b):
            ca, cb = core_name(na), core_name(nb)
            if ca != cb and frozenset({ca, cb}) in pairs:
                return True
    return False


def _all_names(e: dict[str, Any]) -> list[str]:
    return [e["name"], *(e.get("alternate_names") or [])]


def _initials_pair_match(na: str, nb: str) -> bool:
    """True when two names agree under initials expansion — 'C. W. Chapin'
    vs 'Chapin, Chester W.', 'G. Twichell' vs 'Twichell, Ginery'.

    Initials-vs-full-name was the dominant fragmentation cause in the pilot
    (19th-century business records write people as initials). Requires at
    least one exact multi-letter token in common (the surname) and every
    remaining token of the shorter name to match a token of the longer one
    exactly or as an initial.
    """
    ta = [t for t in norm_name(na).split() if t not in _STOP_TOKENS]
    tb = [t for t in norm_name(nb).split() if t not in _STOP_TOKENS]
    if not ta or not tb:
        return False
    short, long_ = (ta, tb) if len(ta) <= len(tb) else (tb, ta)
    if not any(t in long_ for t in short if len(t) > 1):
        return False  # no shared surname — initials alone prove nothing
    remaining = list(long_)
    # Exact multi-letter tokens claim their matches first, so an initial
    # can never greedily consume the surname ('c' must not take 'chapin').
    for t in sorted(short, key=len, reverse=True):
        for cand in remaining:
            if t == cand or (len(t) == 1 and cand.startswith(t)) \
                    or (len(cand) == 1 and t.startswith(cand)):
                remaining.remove(cand)
                break
        else:
            return False
    return True


def initials_compatible(a: dict[str, Any], b: dict[str, Any]) -> bool:
    """Any name pair across the two entities agrees under initials expansion."""
    return any(
        _initials_pair_match(na, nb)
        for na in _all_names(a) for nb in _all_names(b)
    )


def name_similarity(a: dict[str, Any], b: dict[str, Any]) -> float:
    """Best similarity across primary + alternate names of both entities.

    Token-set Jaccard (order-proof: 'Bliss, William' ~ 'William Bliss')
    blended with a character ratio that catches spelling variants. Corporate
    form words count at reduced weight so 'X Railroad Company' vs
    'X Railroad Corporation' differ less than 'X Railroad' vs 'Y Railroad'.
    """
    best = 0.0
    for na in _all_names(a):
        for nb in _all_names(b):
            ta, tb = _tokens(na), _tokens(nb)
            if not ta or not tb:
                continue
            jac = len(ta & tb) / len(ta | tb)
            ratio = SequenceMatcher(None, norm_name(na), norm_name(nb)).ratio()
            best = max(best, 0.6 * jac + 0.4 * ratio)
    return best


_YEAR_RE = re.compile(r"\b(\d{4})\b")


def _year(value: str | None) -> int | None:
    m = _YEAR_RE.search(value or "")
    return int(m.group(1)) if m else None


def dates_contradict(a: dict[str, Any], b: dict[str, Any]) -> str | None:
    """Return a hard contradiction, or None if coexistence is possible.

    Only DISJOINT existence ranges veto (one ended before the other began).
    Differing founding years are deliberately NOT a contradiction: archival
    text records incorporation acts, charters, and opening dates
    interchangeably — the pilot's own Ware River Railroad is stated as 1851,
    1867, and 1873 across three collections. Those discrepancies are routed
    to the LLM adjudicator as evidence instead (see date_discrepancy).
    """
    af, at_ = _year(a.get("exists_from")), _year(a.get("exists_to"))
    bf, bt = _year(b.get("exists_from")), _year(b.get("exists_to"))
    if af and bt and af > bt:
        return f"existence ranges disjoint ({af}- vs -{bt})"
    if bf and at_ and bf > at_:
        return f"existence ranges disjoint ({bf}- vs -{at_})"
    return None


def date_discrepancy(a: dict[str, Any], b: dict[str, Any]) -> str | None:
    """Non-fatal date disagreement (both sides state a differing year)."""
    tol = 2
    af, bf = _year(a.get("exists_from")), _year(b.get("exists_from"))
    if af and bf and abs(af - bf) > tol:
        return f"exists_from differs ({af} vs {bf})"
    at_, bt = _year(a.get("exists_to")), _year(b.get("exists_to"))
    if at_ and bt and abs(at_ - bt) > tol:
        return f"exists_to differs ({at_} vs {bt})"
    return None


def neighbor_overlap(a: dict[str, Any], b: dict[str, Any]) -> float:
    """Jaccard overlap of related-entity names (precomputed per entity).

    'Both have a hasSuccessor edge to Boston and Albany Railroad' is strong
    structural evidence — computed directly as a feature, no graph
    embeddings needed at this scale.
    """
    na, nb = a.get("_neighbors") or set(), b.get("_neighbors") or set()
    if not na or not nb:
        return 0.0
    return len(na & nb) / len(na | nb)


def score_pair(a: dict[str, Any], b: dict[str, Any]) -> tuple[float, str]:
    """Deterministic scorecard. Returns (score, reason)."""
    if a["type"] != b["type"]:
        return 0.0, "type mismatch"
    if a["type"] == "agent" and a.get("agent_type") != b.get("agent_type"):
        return 0.0, "agent_type mismatch"
    contradiction = dates_contradict(a, b)
    if contradiction:
        return 0.0, f"date veto: {contradiction}"

    nsim = name_similarity(a, b)
    # Initials-vs-full-name is how 19th-century records write people
    # ('C. W. Chapin' / 'Chapin, Chester W.') and was the dominant
    # fragmentation cause in the pilot. A compatible pair of PERSON names
    # scores at least 0.8 — into the LLM adjudication band, never
    # auto-merge: initials still need corroborating evidence.
    if (nsim < 0.8 and a.get("agent_type") == "person"
            and b.get("agent_type") == "person"
            and initials_compatible(a, b)):
        nsim = 0.8
    discrepancy = date_discrepancy(a, b)
    if norm_name(a["name"]) == norm_name(b["name"]):
        if discrepancy:
            # Same name but differing stated years: the LLM weighs whether
            # this is incorporation-vs-opening noise or two distinct bodies.
            return 0.88, f"exact normalized name BUT {discrepancy}"
        if a["type"] == "event":
            ya, yb = _year(a.get("date")), _year(b.get("date"))
            if ya and yb and ya != yb:
                return 0.0, f"event year differs ({ya} vs {yb})"
        return 1.0, "exact normalized name"
    nov = neighbor_overlap(a, b)
    score = 0.75 * nsim + 0.25 * nov - (0.08 if discrepancy else 0.0)
    if a["type"] == "event":
        # Cautious event auto-merge: strongly similar names AND the same
        # stated year ("flood November 3 and 4, 1927" / "flood of November
        # 3-4, 1927"). Otherwise events stay exact-match only.
        ya, yb = _year(a.get("date")), _year(b.get("date"))
        if ya and yb and ya == yb and nsim >= 0.55:
            return 1.0, f"event: same year ({ya}) and similar name ({nsim:.2f})"
        return 0.0, f"event kept separate (name={nsim:.2f})"
    reason = f"name={nsim:.2f} neighbors={nov:.2f}"
    if discrepancy:
        reason += f" ({discrepancy})"
    return score, reason


# ---------------------------------------------------------------------------
# LLM adjudication of the borderline band
# ---------------------------------------------------------------------------

def _dossier(e: dict[str, Any]) -> dict[str, Any]:
    return {
        "name": e["name"],
        "alternate_names": e.get("alternate_names") or [],
        **({"agent_type": e.get("agent_type")} if e.get("agent_type") else {}),
        **({"exists_from": e["exists_from"]} if e.get("exists_from") else {}),
        **({"exists_to": e["exists_to"]} if e.get("exists_to") else {}),
        **({"description": e["description"]} if e.get("description") else {}),
        "from_collection": e["_collection_title"],
        "collection_dates": e.get("_collection_dates") or "",
        "related_to": sorted(e.get("_neighbors") or set())[:12],
        "supporting_quotes": e.get("_quotes", [])[:4],
    }


def adjudicate_pair(llm, a: dict[str, Any], b: dict[str, Any]) -> dict[str, Any]:
    """Ask the LLM whether two entity records denote the same real-world
    entity. Returns {"same_entity": bool, "confidence": float, "reason": str}.
    Any parse failure counts as NOT the same entity (under-merge)."""
    from kggenerator.llm import ER_ADJUDICATION_PROMPT  # avoid import cycle at module load

    user = json.dumps({"record_a": _dossier(a), "record_b": _dossier(b)},
                      ensure_ascii=False)
    try:
        raw = llm._chat([
            {"role": "system", "content": ER_ADJUDICATION_PROMPT},
            {"role": "user", "content": user},
        ])
        start, end = raw.find("{"), raw.rfind("}")
        verdict = json.loads(raw[start:end + 1])
        return {
            "same_entity": bool(verdict.get("same_entity")),
            "confidence": float(verdict.get("confidence") or 0.0),
            "reason": str(verdict.get("reason") or "")[:300],
        }
    except Exception as exc:  # noqa: BLE001 — any failure means "keep separate"
        logger.warning("Adjudication failed for %r vs %r (%s); keeping separate.",
                       a["name"], b["name"], exc)
        return {"same_entity": False, "confidence": 0.0,
                "reason": f"adjudication error: {exc}"}


# ---------------------------------------------------------------------------
# Union-find with cluster-time date veto
# ---------------------------------------------------------------------------

class _UnionFind:
    def __init__(self, n: int) -> None:
        self.parent = list(range(n))
        self.members: dict[int, list[int]] = {i: [i] for i in range(n)}

    def find(self, i: int) -> int:
        while self.parent[i] != i:
            self.parent[i] = self.parent[self.parent[i]]
            i = self.parent[i]
        return i

    def union(self, i: int, j: int) -> bool:
        ri, rj = self.find(i), self.find(j)
        if ri == rj:
            return True
        self.parent[rj] = ri
        self.members[ri].extend(self.members.pop(rj))
        return True


# ---------------------------------------------------------------------------
# The resolve pipeline
# ---------------------------------------------------------------------------

def resolve_artifacts(
    artifacts: list[dict[str, Any]], llm=None
) -> tuple[dict[str, Any], dict[str, Any]]:
    """Resolve entities across collection artifacts.

    artifacts: [{collection_uri, collection_title, graph, surface_dates}]
    Returns (merged_graph, decisions).
    """
    pool: list[dict[str, Any]] = []
    for art in artifacts:
        graph = art["graph"]
        names_by_id = {e["id"]: e["name"] for e in graph["entities"]}
        neighbors: dict[str, set[str]] = {e["id"]: set() for e in graph["entities"]}
        quotes: dict[str, list[str]] = {e["id"]: [] for e in graph["entities"]}
        for r in graph["relations"]:
            neighbors[r["from"]].add(norm_name(names_by_id[r["to"]]))
            neighbors[r["to"]].add(norm_name(names_by_id[r["from"]]))
            for eid in (r["from"], r["to"]):
                if r.get("quote") and len(quotes[eid]) < 6:
                    quotes[eid].append(r["quote"])
        for e in graph["entities"]:
            pool.append({
                **e,
                "_collection_uri": art["collection_uri"],
                "_collection_title": art["collection_title"],
                "_collection_dates": art.get("collection_dates") or "",
                "_local_id": e["id"],
                "_neighbors": neighbors[e["id"]],
                "_quotes": quotes[e["id"]],
            })

    # --- Blocking: candidate pairs sharing a significant name token --------
    by_token: dict[tuple[str, str], list[int]] = {}
    for idx, e in enumerate(pool):
        for name in _all_names(e):
            for tok in _tokens(name):
                by_token.setdefault((e["type"], tok), []).append(idx)
    candidate_pairs = {
        (i, j)
        for bucket in by_token.values() if len(bucket) < 200
        for pos, i in enumerate(bucket) for j in bucket[pos + 1:] if i != j
    }
    succ_pairs = successor_pairs(artifacts)
    logger.info("Pooled %d entities from %d collections; %d candidate pairs "
                "after blocking; %d succession-veto name pairs.",
                len(pool), len(artifacts), len(candidate_pairs), len(succ_pairs))

    # --- Score every candidate pair ----------------------------------------
    auto: list[tuple[int, int, str]] = []
    borderline: list[tuple[float, int, int, str]] = []
    decisions: dict[str, Any] = {"auto_merged": [], "llm_adjudicated": [],
                                 "vetoed": [], "near_misses": []}

    def pair_label(i: int, j: int) -> dict[str, str]:
        return {"a": pool[i]["name"], "a_collection": pool[i]["_collection_title"],
                "b": pool[j]["name"], "b_collection": pool[j]["_collection_title"]}

    for i, j in sorted(candidate_pairs):
        a, b = pool[i], pool[j]
        if succession_veto(a, b, succ_pairs):
            if name_similarity(a, b) >= LLM_THRESHOLD:
                decisions["vetoed"].append(
                    {**pair_label(i, j),
                     "reason": "succession veto: extracted graph asserts one "
                               "succeeded the other"})
            continue
        score, reason = score_pair(a, b)
        if reason.startswith(("date veto", "agent_type mismatch")):
            if name_similarity(a, b) >= LLM_THRESHOLD:
                decisions["vetoed"].append({**pair_label(i, j), "reason": reason})
            continue
        if score >= AUTO_THRESHOLD:
            auto.append((i, j, reason))
        elif score >= LLM_THRESHOLD and a["type"] == "agent":
            borderline.append((score, i, j, reason))
        elif score >= LLM_THRESHOLD:
            # Places/events never reach the LLM band — exact match only.
            decisions["near_misses"].append(
                {**pair_label(i, j), "type": a["type"], "score": round(score, 2),
                 "reason": "non-agent kept separate (exact-match-only policy)"})

    # --- Adjudicate the borderline band ------------------------------------
    accepted: list[tuple[int, int]] = [(i, j) for i, j, _ in auto]
    for i, j, reason in auto:
        decisions["auto_merged"].append({**pair_label(i, j), "reason": reason})

    borderline.sort(reverse=True)
    logger.info("%d auto-merge pairs; %d borderline agent pairs for LLM "
                "adjudication.", len(auto), len(borderline))
    for score, i, j, reason in borderline:
        if llm is None:
            decisions["near_misses"].append(
                {**pair_label(i, j), "score": round(score, 2),
                 "reason": "kept separate (--no-llm)"})
            continue
        verdict = adjudicate_pair(llm, pool[i], pool[j])
        decisions["llm_adjudicated"].append(
            {**pair_label(i, j), "score": round(score, 2), **verdict})
        if verdict["same_entity"] and verdict["confidence"] >= 0.6:
            accepted.append((i, j))

    # --- Cluster with transitive date veto ----------------------------------
    uf = _UnionFind(len(pool))
    for i, j in accepted:
        ri, rj = uf.find(i), uf.find(j)
        if ri == rj:
            continue
        conflict = None
        for mi in uf.members[ri]:
            for mj in uf.members[rj]:
                conflict = dates_contradict(pool[mi], pool[mj])
                if not conflict and succession_veto(pool[mi], pool[mj], succ_pairs):
                    conflict = "succession asserted between cluster members"
                if conflict:
                    break
            if conflict:
                break
        if conflict:
            decisions["vetoed"].append(
                {**pair_label(i, j),
                 "reason": f"cluster-time veto: {conflict}"})
            continue
        uf.union(ri, rj)

    clusters: dict[int, list[int]] = {}
    for idx in range(len(pool)):
        clusters.setdefault(uf.find(idx), []).append(idx)

    merged_graph = _assemble(pool, clusters, artifacts)
    decisions["stats"] = {
        "pooled_entities": len(pool),
        "candidate_pairs": len(candidate_pairs),
        "auto_pairs": len(auto),
        "adjudicated_pairs": len(decisions["llm_adjudicated"]),
        "merged_entities": len(merged_graph["entities"]),
        "merged_relations": len(merged_graph["relations"]),
        "clusters_gt1": sum(1 for m in clusters.values() if len(m) > 1),
    }
    return merged_graph, decisions


def _assemble(
    pool: list[dict[str, Any]],
    clusters: dict[int, list[int]],
    artifacts: list[dict[str, Any]],
) -> dict[str, Any]:
    """Emit one canonical entity per cluster and remap/dedupe relations."""
    canonical: list[dict[str, Any]] = []
    canon_id_of: dict[tuple[str, str], str] = {}  # (collection_uri, local_id) -> id

    for members in clusters.values():
        ents = [pool[i] for i in members]
        primary = max(ents, key=lambda e: (len(e["name"]), e.get("confidence") or 0))
        cid = f"m{len(canonical) + 1}"
        alt = sorted({
            n for e in ents for n in _all_names(e) if n != primary["name"]
        })
        merged: dict[str, Any] = {
            "id": cid,
            "type": primary["type"],
            **({"agent_type": primary["agent_type"]}
               if primary.get("agent_type") else {}),
            "name": primary["name"],
            "alternate_names": alt,
            "confidence": max(float(e.get("confidence") or 0.5) for e in ents),
            "source_uri": sorted({u for e in ents for u in e.get("source_uri", [])}),
            "members": [
                {"collection_uri": e["_collection_uri"],
                 "collection_title": e["_collection_title"],
                 "local_id": e["_local_id"], "name": e["name"]}
                for e in ents
            ],
        }
        for field in ("description", "exists_from", "exists_to",
                      "event_type", "date"):
            vals = [str(e.get(field) or "").strip() for e in ents]
            vals = [v for v in vals if v]
            if vals:
                merged[field] = max(vals, key=len)
        canonical.append(merged)
        for e in ents:
            canon_id_of[(e["_collection_uri"], e["_local_id"])] = cid

    relations: dict[tuple[str, str, str], dict[str, Any]] = {}
    for art in artifacts:
        for r in art["graph"]["relations"]:
            src = canon_id_of[(art["collection_uri"], r["from"])]
            dst = canon_id_of[(art["collection_uri"], r["to"])]
            if src == dst:
                continue  # endpoints merged into one entity
            key = (src, dst, r["type"])
            m = relations.setdefault(key, {
                "from": src, "to": dst, "type": r["type"],
                "source_uri": [], "quotes": [], "confidence": 0.0,
            })
            m["source_uri"] = sorted(set(m["source_uri"]) | set(r.get("source_uri", [])))
            q = str(r.get("quote") or "").strip()
            if q and q not in m["quotes"] and len(m["quotes"]) < 3:
                m["quotes"].append(q)
            m["confidence"] = max(m["confidence"], float(r.get("confidence") or 0.5))
            for field in ("date", "nature"):
                val = str(r.get(field) or "").strip()
                if val and not m.get(field):
                    m[field] = val

    return {"entities": canonical, "relations": list(relations.values())}
