"""Curated RiC-O 1.1 relation table. GENERATED — do not edit by hand.

Regenerate with scripts/generate_rico_relations.py after changing the
curated list; the generator validates every entry against the ontology.
"""

RICO_RELATIONS: list[dict] = [
    {
        'name': 'hasOrHadCorrespondent',
        'inverse': None,
        'category': 'agent-agent',
        'hint': 'A exchanged letters or other correspondence with B (symmetric).',
        'neo4j_type': 'RICO_HAS_OR_HAD_CORRESPONDENT',
        'inverse_neo4j_type': 'RICO_HAS_OR_HAD_CORRESPONDENT',
        'uri': 'https://www.ica.org/standards/RiC/ontology#hasOrHadCorrespondent',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#hasOrHadCorrespondent',
        'definition': 'Connects two Persons that correspond or have corresponded with each other. This relation is symmetric.',
    },
    {
        'name': 'hasOrHadEmployer',
        'inverse': 'isOrWasEmployerOf',
        'category': 'agent-agent',
        'hint': 'Person A was employed by agent B.',
        'neo4j_type': 'RICO_HAS_OR_HAD_EMPLOYER',
        'inverse_neo4j_type': 'RICO_IS_OR_WAS_EMPLOYER_OF',
        'uri': 'https://www.ica.org/standards/RiC/ontology#hasOrHadEmployer',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#isOrWasEmployerOf',
        'definition': "Inverse of 'is or was employer of' object property.",
    },
    {
        'name': 'hasOrHadManager',
        'inverse': 'isOrWasManagerOf',
        'category': 'agent-agent',
        'hint': 'A was managed or administered by person B.',
        'neo4j_type': 'RICO_HAS_OR_HAD_MANAGER',
        'inverse_neo4j_type': 'RICO_IS_OR_WAS_MANAGER_OF',
        'uri': 'https://www.ica.org/standards/RiC/ontology#hasOrHadManager',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#isOrWasManagerOf',
        'definition': "Inverse of 'is or was manager of' object property.",
    },
    {
        'name': 'hasOrHadLeader',
        'inverse': 'isOrWasLeaderOf',
        'category': 'agent-agent',
        'hint': 'Corporate body or group A was led by B (president, chairman, director, superintendent).',
        'neo4j_type': 'RICO_HAS_OR_HAD_LEADER',
        'inverse_neo4j_type': 'RICO_IS_OR_WAS_LEADER_OF',
        'uri': 'https://www.ica.org/standards/RiC/ontology#hasOrHadLeader',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#isOrWasLeaderOf',
        'definition': "Inverse of 'is or was leader of' object property.",
    },
    {
        'name': 'hasOrHadMember',
        'inverse': 'isOrWasMemberOf',
        'category': 'agent-agent',
        'hint': 'Group, family, or corporate body A had B as a member.',
        'neo4j_type': 'RICO_HAS_OR_HAD_MEMBER',
        'inverse_neo4j_type': 'RICO_IS_OR_WAS_MEMBER_OF',
        'uri': 'https://www.ica.org/standards/RiC/ontology#hasOrHadMember',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#isOrWasMemberOf',
        'definition': 'Connects a Group to a Person that is or was a member of that Group.',
    },
    {
        'name': 'hasOrHadOwner',
        'inverse': 'isOrWasOwnerOf',
        'category': 'agent-agent',
        'hint': 'A was owned by agent B.',
        'neo4j_type': 'RICO_HAS_OR_HAD_OWNER',
        'inverse_neo4j_type': 'RICO_IS_OR_WAS_OWNER_OF',
        'uri': 'https://www.ica.org/standards/RiC/ontology#hasOrHadOwner',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#isOrWasOwnerOf',
        'definition': "Inverse of 'is or was owner of' object property.",
    },
    {
        'name': 'hasOrHadController',
        'inverse': 'isOrWasControllerOf',
        'category': 'agent-agent',
        'hint': 'Corporate body A was controlled by B (parent company, holding company, controlling lessee).',
        'neo4j_type': 'RICO_HAS_OR_HAD_CONTROLLER',
        'inverse_neo4j_type': 'RICO_IS_OR_WAS_CONTROLLER_OF',
        'uri': 'https://www.ica.org/standards/RiC/ontology#hasOrHadController',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#isOrWasControllerOf',
        'definition': "Inverse of 'is or was controller of' object property.",
    },
    {
        'name': 'hasOrHadSubdivision',
        'inverse': 'isOrWasSubdivisionOf',
        'category': 'agent-agent',
        'hint': 'Corporate body A had B as a subdivision, department, or branch.',
        'neo4j_type': 'RICO_HAS_OR_HAD_SUBDIVISION',
        'inverse_neo4j_type': 'RICO_IS_OR_WAS_SUBDIVISION_OF',
        'uri': 'https://www.ica.org/standards/RiC/ontology#hasOrHadSubdivision',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#isOrWasSubdivisionOf',
        'definition': 'Connects a Group to one of its present or past subdivisions.',
    },
    {
        'name': 'hasSuccessor',
        'inverse': 'isSuccessorOf',
        'category': 'agent-agent',
        'hint': 'Agent A was succeeded by B (corporate reorganization, merger, renamed entity).',
        'neo4j_type': 'RICO_HAS_SUCCESSOR',
        'inverse_neo4j_type': 'RICO_IS_SUCCESSOR_OF',
        'uri': 'https://www.ica.org/standards/RiC/ontology#hasSuccessor',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#isSuccessorOf',
        'definition': 'Connects an Agent to another Agent that succeeds it chronologically.',
    },
    {
        'name': 'hasOrHadAuthorityOver',
        'inverse': 'isOrWasUnderAuthorityOf',
        'category': 'agent-agent',
        'hint': 'A held authority over B.',
        'neo4j_type': 'RICO_HAS_OR_HAD_AUTHORITY_OVER',
        'inverse_neo4j_type': 'RICO_IS_OR_WAS_UNDER_AUTHORITY_OF',
        'uri': 'https://www.ica.org/standards/RiC/ontology#hasOrHadAuthorityOver',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#isOrWasUnderAuthorityOf',
        'definition': 'Connects an Agent to a Thing over which the Agent has or had some kind of authority.',
    },
    {
        'name': 'hasOrHadSpouse',
        'inverse': None,
        'category': 'agent-agent',
        'hint': 'A and B were married (symmetric).',
        'neo4j_type': 'RICO_HAS_OR_HAD_SPOUSE',
        'inverse_neo4j_type': 'RICO_HAS_OR_HAD_SPOUSE',
        'uri': 'https://www.ica.org/standards/RiC/ontology#hasOrHadSpouse',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#hasOrHadSpouse',
        'definition': 'Connects two Persons who are or were married. This relation is symmetric.',
    },
    {
        'name': 'hasChild',
        'inverse': 'isChildOf',
        'category': 'agent-agent',
        'hint': 'Person A had child B.',
        'neo4j_type': 'RICO_HAS_CHILD',
        'inverse_neo4j_type': 'RICO_IS_CHILD_OF',
        'uri': 'https://www.ica.org/standards/RiC/ontology#hasChild',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#isChildOf',
        'definition': 'Connects a Person to one of their children.',
    },
    {
        'name': 'hasSibling',
        'inverse': None,
        'category': 'agent-agent',
        'hint': 'A and B were siblings (symmetric).',
        'neo4j_type': 'RICO_HAS_SIBLING',
        'inverse_neo4j_type': 'RICO_HAS_SIBLING',
        'uri': 'https://www.ica.org/standards/RiC/ontology#hasSibling',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#hasSibling',
        'definition': 'Connects two Persons who are siblings. This relation is symmetric.',
    },
    {
        'name': 'hasAncestor',
        'inverse': 'hasDescendant',
        'category': 'agent-agent',
        'hint': 'Person A had ancestor B (beyond parent/child).',
        'neo4j_type': 'RICO_HAS_ANCESTOR',
        'inverse_neo4j_type': 'RICO_HAS_DESCENDANT',
        'uri': 'https://www.ica.org/standards/RiC/ontology#hasAncestor',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#hasDescendant',
        'definition': "Inverse of 'has descendant' object property. This is a transitive relation.",
    },
    {
        'name': 'hasOrHadTeacher',
        'inverse': 'hasOrHadStudent',
        'category': 'agent-agent',
        'hint': 'Person A was taught or mentored by B.',
        'neo4j_type': 'RICO_HAS_OR_HAD_TEACHER',
        'inverse_neo4j_type': 'RICO_HAS_OR_HAD_STUDENT',
        'uri': 'https://www.ica.org/standards/RiC/ontology#hasOrHadTeacher',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#hasOrHadStudent',
        'definition': 'Connects a Person to another Person who is or was their teacher.',
    },
    {
        'name': 'knows',
        'inverse': None,
        'category': 'agent-agent',
        'hint': 'A and B knew each other personally (symmetric); use only when no more specific relation fits.',
        'neo4j_type': 'RICO_KNOWS',
        'inverse_neo4j_type': 'RICO_KNOWS',
        'uri': 'https://www.ica.org/standards/RiC/ontology#knows',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#knows',
        'definition': 'Connects two Persons that directly know each other during their existence. This relation is symmetric.',
    },
    {
        'name': 'agentHasOrHadLocation',
        'inverse': 'isOrWasLocationOfAgent',
        'category': 'agent-place',
        'hint': 'Agent A was located or headquartered at place B.',
        'neo4j_type': 'RICO_AGENT_HAS_OR_HAD_LOCATION',
        'inverse_neo4j_type': 'RICO_IS_OR_WAS_LOCATION_OF_AGENT',
        'uri': 'https://www.ica.org/standards/RiC/ontology#agentHasOrHadLocation',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#isOrWasLocationOfAgent',
        'definition': "Inverse of 'is or was location of agent' object property.",
    },
    {
        'name': 'hasBirthPlace',
        'inverse': 'isBirthPlaceOf',
        'category': 'agent-place',
        'hint': 'Person A was born at place B.',
        'neo4j_type': 'RICO_HAS_BIRTH_PLACE',
        'inverse_neo4j_type': 'RICO_IS_BIRTH_PLACE_OF',
        'uri': 'https://www.ica.org/standards/RiC/ontology#hasBirthPlace',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#isBirthPlaceOf',
        'definition': "Inverse of 'is birth place of' object property.",
    },
    {
        'name': 'hasDeathPlace',
        'inverse': 'isDeathPlaceOf',
        'category': 'agent-place',
        'hint': 'Person A died at place B.',
        'neo4j_type': 'RICO_HAS_DEATH_PLACE',
        'inverse_neo4j_type': 'RICO_IS_DEATH_PLACE_OF',
        'uri': 'https://www.ica.org/standards/RiC/ontology#hasDeathPlace',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#isDeathPlaceOf',
        'definition': "Inverse of 'is death place of' object property.",
    },
    {
        'name': 'isAssociatedWithPlace',
        'inverse': 'isPlaceAssociatedWith',
        'category': 'any-place',
        'hint': 'A (agent or event) is associated with place B (area of operations or activity).',
        'neo4j_type': 'RICO_IS_ASSOCIATED_WITH_PLACE',
        'inverse_neo4j_type': 'RICO_IS_PLACE_ASSOCIATED_WITH',
        'uri': 'https://www.ica.org/standards/RiC/ontology#isAssociatedWithPlace',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#isPlaceAssociatedWith',
        'definition': "Inverse of 'is place associated with' object property.",
    },
    {
        'name': 'hasOrHadParticipant',
        'inverse': 'isOrWasParticipantIn',
        'category': 'event-agent',
        'hint': 'Event A had agent B as a participant.',
        'neo4j_type': 'RICO_HAS_OR_HAD_PARTICIPANT',
        'inverse_neo4j_type': 'RICO_IS_OR_WAS_PARTICIPANT_IN',
        'uri': 'https://www.ica.org/standards/RiC/ontology#hasOrHadParticipant',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#isOrWasParticipantIn',
        'definition': 'Connects an Event to a Thing that is or was actively or passively involved in it.',
    },
    {
        'name': 'isAssociatedWithEvent',
        'inverse': 'isEventAssociatedWith',
        'category': 'any-event',
        'hint': 'A is associated with event B (affected by it, subject of it).',
        'neo4j_type': 'RICO_IS_ASSOCIATED_WITH_EVENT',
        'inverse_neo4j_type': 'RICO_IS_EVENT_ASSOCIATED_WITH',
        'uri': 'https://www.ica.org/standards/RiC/ontology#isAssociatedWithEvent',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#isEventAssociatedWith',
        'definition': "Inverse of 'is event associated with' object property.",
    },
    {
        'name': 'hasOrHadSubevent',
        'inverse': 'isOrWasSubeventOf',
        'category': 'event-event',
        'hint': 'Event A included B as a subevent.',
        'neo4j_type': 'RICO_HAS_OR_HAD_SUBEVENT',
        'inverse_neo4j_type': 'RICO_IS_OR_WAS_SUBEVENT_OF',
        'uri': 'https://www.ica.org/standards/RiC/ontology#hasOrHadSubevent',
        'inverse_uri': 'https://www.ica.org/standards/RiC/ontology#isOrWasSubeventOf',
        'definition': 'Connects an Event to one of a series of Events that constitute the original, broader, past or ongoing Event.',
    },
]

RELATIONS_BY_NAME = {r['name']: r for r in RICO_RELATIONS}
