apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: keycloak
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
stringData:
  admin-password:    {{ .Values.keycloak.adminPassword | quote }}
  postgres-password: {{ .Values.postgres.password | quote }}
