apiVersion: v1
kind: PersistentVolume
metadata:
  name: vllm-pv
  labels:
    app: vllm
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: {{ .Values.persistence.hostPath | quote }}
    type: DirectoryOrCreate
