apiVersion: v1
kind: Secret
metadata:
  name: asapbackend-secret
  labels:
    app: asapbackend
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
stringData:
  inference-api-key: {{ .Values.secrets.inferenceApiKey | quote }}
