apiVersion: v1
kind: Service
metadata:
  name: asapbackend
  labels:
    app: asapbackend
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: ClusterIP
  selector:
    app: asapbackend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
