apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc
  labels:
    app: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  # Bind explicitly to the neo4j-pv PersistentVolume via label selector.
  selector:
    matchLabels:
      app: neo4j
