apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
  labels:
    app: neo4j
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
stringData:
  neo4j-password: {{ .Values.auth.password | quote }}
  neo4j-auth: {{ printf "neo4j/%s" .Values.auth.password | quote }}
  neo4j-uri: {{ .Values.auth.uri | quote }}
  neo4j-user: {{ .Values.auth.user | quote }}
