apiVersion: v1
kind: Service
metadata:
  name: graphdb
  labels:
    app: neo4j
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: ClusterIP
  selector:
    app: neo4j
  ports:
    - name: http
      port: 7474
      targetPort: http
    - name: bolt
      port: 7687
      targetPort: bolt
