apiVersion: v1
kind: Secret
metadata:
  name: archivesspace-secret
  labels:
    app: asapextractor
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
stringData:
  archivessnake.yml: |
    baseurl: {{ .Values.aspace.baseurl | quote }}
    username: {{ .Values.aspace.username | quote }}
    password: {{ .Values.aspace.password | quote }}
