apiVersion: v1
kind: Service
metadata:
  name: asapui
  labels:
    app: asapui
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: ClusterIP
  selector:
    app: asapui
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
